### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by victorbjorn**
Probably typo?

### CODE REVIEW

**Comment by lmajano** [comment]
It actually is an expression commonly use to express belonging for the subject. So I am not sure to change it, unless this was not understood?

**Comment by victorbjorn** [comment]
Aha! Then it makes sense, thank you. Sorry, I'm not a native English speaker.

**Comment by lmajano** [comment]
No worries, me neither :)

**Comment by bdw429s** [comment]
"sport" as a verb means 

```
wear or display (a distinctive or noticeable item).
```

While the usage is correct, it's not super common so I could see there being confusion since it also looks so similar to the word "supports" which also makes sense.

**Comment by lmajano** [comment]
That's why I left it open, I agree with changing it, just trying to see if we can rewrite all of it to something more standard English.

**Pull request merged**
