### PR TITLE
Fixing a typo.

### PR DESCRIPTION
**Pull request by nolanerck**

### CODE REVIEW

**Comment by bdw429s** [comment]
@nolanerck Not really a "typo" per se.  The ColdBox framework uses the variable name `event` to refer to the `RequestContext` CFC instance and it is an "object" technically.  @lmajano which do you prefer?

**Comment by nolanerck** [comment]
@bdw429s to me "request context" means I can do:

dump( rc )

...and I'll see getResponse() as a valid method. That doesn't work.

But if i do:

dump( event )

...I do indeed see getResponse(), which is why I think my update is more correct.

**Comment by lmajano** [comment]
I get what you mean, thanks

**Comment by bdw429s** [comment]
@nolanerck I think you've confused two different things that happen to have the same acronym.  

* Request Context - this is passed to actions as the `event` variable and is a CFC instance.  The `getReponse()` method lives here.
* Request Collection - This is passed to actions as the `rc` variable and is a struct stored inside the Request Context which contains the form and URL variables.  (Also accessible via `event.getCollection()`.

I've heard people (even presenting at CF conferences!) call the request collection (`rc` variable) by the name request context, but that is incorrect.  The context is the CFC instance.  The collection is the struct stored inside the context. 

So when you dump the request collection, i.e.
```
dump( rc )
```
you would not see this method.  You would need to dump the request context, to see the method
```
dump( event )
```
My advice would be not to remove the phrase "request context", therefore pertuating people's confusion, but to use both like so:

> ... object via the request context's `event.getResponse()` method.

which would help reinforce what the request context is.

**Pull request merged**
